In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/Sales_data.csv")
data.head(5)

   OrderId   Product  Price
0        1    Laptop   5000
1        2     Phone  20000
2        3    Tablet  30000
3        4   Monitor  15000
4        5  Keyboard   2000

In [ ]:
data.isna().sum()

OrderId    0
Product    0
Price      0
dtype: int64

In [ ]:
data = data.dropna()

In [ ]:
data['tax']=data['Price']*1.18
data.head(10)

   OrderId     Product  Price      tax
0        1      Laptop   5000   5900.0
1        2       Phone  20000  23600.0
2        3      Tablet  30000  35400.0
3        4     Monitor  15000  17700.0
4        5    Keyboard   2000   2360.0
5        6       Mouse   1000   1180.0
6        7     Printer  12000  14160.0
7        8  Headphones   3000   3540.0
8        9      Camera  25000  29500.0
9       10     Speaker   4000   4720.0

In [ ]:
import sqlite3
conn = sqlite3.connect("sales.db")
data.to_sql("sales_table",conn,if_exists= "replace",index=False)
print("Data loaded successfully")

Data loaded successfully